import { ICountry } from "../types/index";
import { Permission } from "@/types";
export const roleHierarchy: { [key: string]: string[] } = {
  master_admin: [
    "country_admin",
    "partner",
    "companies",
    "super_agent",
    "sub_agents",
  ],
  country_admin: ["partner", "companies", "super_agent", "sub_agents"],
  partner: ["companies", "super_agent", "sub_agents"],
  companies: ["super_agent", "sub_agents"],
  super_agent: ["sub_agents"],
  sub_agent: [],
};
export const dummyBroadcastData = [
  {
    id: "01",
    title: "How to add a country admin",
    audience: "Country Admin",
    deliveryChannel: "In-App Notification",
    timeStamp: "2024-02-20 12:00:00",
    status: "Scheduled",
  },
  {
    id: "02",
    title: "How to add a partner",
    audience: "Partner",
    deliveryChannel: "SMS",
    timeStamp: "2024-02-20 12:00:00",
    status: "Draft",
  },
  {
    id: "03",
    title: "How to add a company",
    audience: "Company",
    deliveryChannel: "Push notification",
    timeStamp: "2024-02-20 12:00:00",
    status: "Sent",
  },
  {
    id: "04",
    title: "How to add a super agent",
    audience: "Super Agent",
    deliveryChannel: "Email notification",
    timeStamp: "2024-02-20 12:00:00",
    status: "Scheduled",
  },
  {
    id: "05",
    title: "How to add a sub agent",
    audience: "Company",
    deliveryChannel: "Email notification",
    timeStamp: "2024-02-20 12:00:00",
    status: "Draft",
  },
  {
    id: "06",
    title: "How to add a sub agent",
    audience: "Partner",
    deliveryChannel: "SMS",
    timeStamp: "2024-02-20 12:00:00",
    status: "Draft",
  },
  {
    id: "07",
    title: "Verido Help Video",
    audience: "Super Agent",
    deliveryChannel: "Push notification",
    timeStamp: "2024-02-20 12:00:00",
    status: "Sent",
  },
];

export const countryData: ICountry[] = [
  {
    country: "Nigeria",
    partners: 56,
    consultants: 1003,
    businesses: 2693,
    subscribers: 723,
  },
  {
    country: "Kenya",
    partners: 56,
    consultants: 1003,
    businesses: 2693,
    subscribers: 723,
  },
  {
    country: "Uganda",
    partners: 56,
    consultants: 1003,
    businesses: 2693,
    subscribers: 723,
  },
  {
    country: "Mozambique",
    partners: 56,
    consultants: 1003,
    businesses: 2693,
    subscribers: 723,
  },
  {
    country: "Ghana",
    partners: 56,
    consultants: 1003,
    businesses: 2693,
    subscribers: 723,
  },
  {
    country: "South Africa",
    partners: 56,
    consultants: 1003,
    businesses: 2693,
    subscribers: 723,
  },
];

export const monthNames = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const countryRevenueData = [
  { label: "🇬🇧 United Kingdom", value: "$57,000" },
  { label: "🇳🇬 Nigeria", value: "$40,000" },
  { label: "🇰🇪 Kenya", value: "$36,000" },
  { label: "🇩🇪 Germany", value: "$30,000" },
  { label: "🇦🇺 Australia", value: "$27,000" },
];
export const partnerRevenueData = [
  { label: "Invasion", value: "$57,000" },
  { label: "Figma", value: "$40,000" },
  { label: "Trello", value: "$36,000" },
  { label: "Google", value: "$30,000" },
  { label: "Infogenix", value: "$27,000" },
];
export const companyRevenueData = [
  { label: "Avon Products", value: "$57,000" },
  { label: "NCR Coperation", value: "$40,000" },
  { label: "Navistar International Corporation", value: "$36,000" },
  { label: "Ball Corporation", value: "$30,000" },
  { label: "Baker Hughes Incorporated", value: "$27,000" },
];
export const superAgentsRevenueData = [
  { label: "Mary Dokubo", value: "$57,000" },
  { label: "Joseph Opuene", value: "$40,000" },
  { label: "Sarah Suoyo", value: "$36,000" },
  { label: "Simon Nwosu", value: "$30,000" },
  { label: "Sarah Werinipre", value: "$27,000" },
];
export const subAgentsRevenueData = [
  { label: "Mary Dokubo", value: "$57,000" },
  { label: "Joseph Opuene", value: "$40,000" },
  { label: "Sarah Suoyo", value: "$36,000" },
  { label: "Simon Nwosu", value: "$30,000" },
  { label: "Sarah Werinipre", value: "$27,000" },
];

export const cardData = [
  {
    title: "Total Users",
    value: 0,
    background: "#E6F6EA",
    icon: "/assets/icons/green-trend.svg",
    roles: [
      "master_admin",
      "country_admin",
      "companies",
      "partner",
      "distributor",
    ],
  },
  {
    title: "Country Admin",
    value: 0,
    background: "#FFF4E6",
    icon: "/assets/icons/purple-trend.svg",
    roles: ["master_admin"],
  },
  {
    title: "Partners",
    value: 0,
    background: "#E6F2F2",
    icon: "/assets/icons/orange-trend.svg",
    roles: ["master_admin", "country_admin"],
  },
  {
    title: "Companies",
    value: 0,
    background: "#F1EEFB",
    icon: "/assets/icons/red-trend.svg",
    roles: ["master_admin", "country_admin", "partner"],
  },
  {
    title: "Super Agents",
    value: 0,
    background: "#FFE8E5",
    icon: "/assets/icons/blue-trend.svg",
    roles: ["master_admin", "country_admin", "companies", "partner"],
  },
  {
    title: "Sub Agents",
    value: 0,
    background: "#E6F2FF",
    icon: "/assets/icons/teal-trend.svg",
    roles: [
      "master_admin",
      "country_admin",
      "companies",
      "partner",
      "super_agent",
    ],
  },
  {
    title: "Digital Entrepreneurs",
    value: 0,
    background: "#E6F6EA",
    icon: "/assets/icons/green-trend.svg",
    roles: ["master_admin", "country_admin"],
  },
  {
    title: "Distributors",
    value: 0,
    background: "#FFF4E6",
    icon: "/assets/icons/purple-trend.svg",
    roles: ["master_admin", "country_admin"],
  },
  {
    title: "Multibranch Businesses",
    value: 0,
    background: "#E6F2F2",
    icon: "/assets/icons/orange-trend.svg",
    roles: ["master_admin", "country_admin"],
  },
  {
    title: "Business Owners",
    value: 0,
    background: "#E6F2F2",
    icon: "/assets/icons/orange-trend.svg",
    roles: ["digital_entrepreneur", "master_admin", "country_admin"],
  },
  {
    title: "Branches",
    value: 0,
    background: "#E6F2F2",
    icon: "/assets/icons/orange-trend.svg",
    roles: ["multi_branch_business", "distributor"],
  },
];

export const listOfUsers = [
  "master_admin",
  "country_admin",
  "company",
  "partner",
  "super_agent",
  "sub_agent",
];

export const businessAnalyticsData = [
  {
    title: "Total Users",
    value: 200,
    background: "#E6F6EA",
    icon: "/assets/icons/green-trend.svg",
  },
  {
    title: "Suscribed Users",
    value: 180,
    background: "#E6F2F2",
    icon: "/assets/icons/orange-trend.svg",
  },
  {
    title: "Unsubscribed Users",
    value: 20,
    background: "#E6F2FF",
    icon: "/assets/icons/teal-trend.svg",
  },
];

export const subscriptionMockData = [
  {
    title: "Email Notifications",
    value: 200,
    background: "#E6F6EA",
    icon: "/assets/icons/green-trend.svg",
  },
];
export const deliveryChannels = [
  { value: "inApp", label: "In-App Notification" },
  { value: "email", label: "Email" },
  { value: "push", label: "Push Notification" },
];

export const currencies = [
  { code: "USD", symbol: "$", name: "US Dollar" },
  { code: "EUR", symbol: "€", name: "Euro" },
  { code: "GBP", symbol: "£", name: "British Pound" },
  { code: "NGN", symbol: "₦", name: "Nigerian Naira" },
  { code: "KES", symbol: "KSh", name: "Kenyan Shilling" },
  { code: "UGX", symbol: "USh", name: "Ugandan Shilling" },
  { code: "MZN", symbol: "MT", name: "Mozambican Metical" },
  { code: "GHS", symbol: "GH₵", name: "Ghanaian Cedi" },
  { code: "ZAR", symbol: "R", name: "South African Rand" },
  { code: "TZS", symbol: "TSh", name: "Tanzanian Shilling" },
  { code: "RWF", symbol: "RF", name: "Rwandan Franc" },
  { code: "ETB", symbol: "Br", name: "Ethiopian Birr" },
  { code: "EGP", symbol: "E£", name: "Egyptian Pound" },
  { code: "MAD", symbol: "د.م.", name: "Moroccan Dirham" },
  { code: "XOF", symbol: "CFA", name: "West African CFA Franc" },
  { code: "XAF", symbol: "FCFA", name: "Central African CFA Franc" },
  { code: "AUD", symbol: "A$", name: "Australian Dollar" },
  { code: "CAD", symbol: "C$", name: "Canadian Dollar" },
  { code: "CHF", symbol: "Fr", name: "Swiss Franc" },
  { code: "CNY", symbol: "¥", name: "Chinese Yuan" },
  { code: "JPY", symbol: "¥", name: "Japanese Yen" },
  { code: "INR", symbol: "₹", name: "Indian Rupee" },
  { code: "SGD", symbol: "S$", name: "Singapore Dollar" },
  { code: "AED", symbol: "د.إ", name: "UAE Dirham" },
  { code: "SAR", symbol: "﷼", name: "Saudi Riyal" },
  { code: "AFN", symbol: "؋", name: "Afghan Afghani" },
  { code: "ALL", symbol: "L", name: "Albanian Lek" },
  { code: "AMD", symbol: "֏", name: "Armenian Dram" },
  { code: "ANG", symbol: "ƒ", name: "Netherlands Antillean Guilder" },
  { code: "AOA", symbol: "Kz", name: "Angolan Kwanza" },
  { code: "ARS", symbol: "$", name: "Argentine Peso" },
  { code: "AWG", symbol: "ƒ", name: "Aruban Florin" },
  { code: "AZN", symbol: "₼", name: "Azerbaijani Manat" },
  { code: "BAM", symbol: "KM", name: "Bosnia-Herzegovina Convertible Mark" },
  { code: "BBD", symbol: "Bds$", name: "Barbadian Dollar" },
  { code: "BDT", symbol: "৳", name: "Bangladeshi Taka" },
  { code: "BGN", symbol: "лв", name: "Bulgarian Lev" },
  { code: "BHD", symbol: ".د.ب", name: "Bahraini Dinar" },
  { code: "BIF", symbol: "FBu", name: "Burundian Franc" },
  { code: "BMD", symbol: "BD$", name: "Bermudan Dollar" },
  { code: "BND", symbol: "B$", name: "Brunei Dollar" },
  { code: "BOB", symbol: "Bs.", name: "Bolivian Boliviano" },
  { code: "BRL", symbol: "R$", name: "Brazilian Real" },
  { code: "BSD", symbol: "B$", name: "Bahamian Dollar" },
  { code: "BTN", symbol: "Nu.", name: "Bhutanese Ngultrum" },
  { code: "BWP", symbol: "P", name: "Botswanan Pula" },
  { code: "BYN", symbol: "Br", name: "Belarusian Ruble" },
  { code: "BZD", symbol: "BZ$", name: "Belize Dollar" },
  { code: "CDF", symbol: "FC", name: "Congolese Franc" },
  { code: "CLP", symbol: "$", name: "Chilean Peso" },
  { code: "COP", symbol: "$", name: "Colombian Peso" },
  { code: "CRC", symbol: "₡", name: "Costa Rican Colón" },
  { code: "CUC", symbol: "CUC$", name: "Cuban Convertible Peso" },
  { code: "CUP", symbol: "₱", name: "Cuban Peso" },
  { code: "CVE", symbol: "$", name: "Cape Verdean Escudo" },
  { code: "CZK", symbol: "Kč", name: "Czech Koruna" },
  { code: "DJF", symbol: "Fdj", name: "Djiboutian Franc" },
  { code: "DKK", symbol: "kr", name: "Danish Krone" },
  { code: "DOP", symbol: "RD$", name: "Dominican Peso" },
  { code: "DZD", symbol: "د.ج", name: "Algerian Dinar" },
  { code: "ERN", symbol: "Nfk", name: "Eritrean Nakfa" },
  { code: "FJD", symbol: "FJ$", name: "Fijian Dollar" },
  { code: "FKP", symbol: "£", name: "Falkland Islands Pound" },
  { code: "GMD", symbol: "D", name: "Gambian Dalasi" },
  { code: "GNF", symbol: "FG", name: "Guinean Franc" },
  { code: "GTQ", symbol: "Q", name: "Guatemalan Quetzal" },
  { code: "GYD", symbol: "G$", name: "Guyanese Dollar" },
  { code: "HKD", symbol: "HK$", name: "Hong Kong Dollar" },
  { code: "HNL", symbol: "L", name: "Honduran Lempira" },
  { code: "HRK", symbol: "kn", name: "Croatian Kuna" },
  { code: "HTG", symbol: "G", name: "Haitian Gourde" },
  { code: "HUF", symbol: "Ft", name: "Hungarian Forint" },
  { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
  { code: "ILS", symbol: "₪", name: "Israeli New Shekel" },
  { code: "IQD", symbol: "ع.د", name: "Iraqi Dinar" },
  { code: "IRR", symbol: "﷼", name: "Iranian Rial" },
  { code: "ISK", symbol: "kr", name: "Icelandic Króna" },
  { code: "JMD", symbol: "J$", name: "Jamaican Dollar" },
  { code: "JOD", symbol: "د.ا", name: "Jordanian Dinar" },
  { code: "KGS", symbol: "с", name: "Kyrgystani Som" },
  { code: "KHR", symbol: "៛", name: "Cambodian Riel" },
  { code: "KMF", symbol: "CF", name: "Comorian Franc" },
  { code: "KPW", symbol: "₩", name: "North Korean Won" },
  { code: "KRW", symbol: "₩", name: "South Korean Won" },
  { code: "KWD", symbol: "د.ك", name: "Kuwaiti Dinar" },
  { code: "KYD", symbol: "CI$", name: "Cayman Islands Dollar" },
  { code: "KZT", symbol: "₸", name: "Kazakhstani Tenge" },
  { code: "LAK", symbol: "₭", name: "Laotian Kip" },
  { code: "LBP", symbol: "ل.ل", name: "Lebanese Pound" },
  { code: "LKR", symbol: "Rs", name: "Sri Lankan Rupee" },
  { code: "LRD", symbol: "L$", name: "Liberian Dollar" },
  { code: "LSL", symbol: "M", name: "Lesotho Loti" },
  { code: "LYD", symbol: "ل.د", name: "Libyan Dinar" },
  { code: "MDL", symbol: "L", name: "Moldovan Leu" },
  { code: "MGA", symbol: "Ar", name: "Malagasy Ariary" },
  { code: "MKD", symbol: "ден", name: "Macedonian Denar" },
  { code: "MMK", symbol: "K", name: "Myanmar Kyat" },
  { code: "MNT", symbol: "₮", name: "Mongolian Tugrik" },
  { code: "MOP", symbol: "MOP$", name: "Macanese Pataca" },
  { code: "MRU", symbol: "UM", name: "Mauritanian Ouguiya" },
  { code: "MUR", symbol: "₨", name: "Mauritian Rupee" },
  { code: "MVR", symbol: "Rf", name: "Maldivian Rufiyaa" },
  { code: "MWK", symbol: "MK", name: "Malawian Kwacha" },
  { code: "MXN", symbol: "$", name: "Mexican Peso" },
  { code: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
  { code: "NAD", symbol: "N$", name: "Namibian Dollar" },
  { code: "NIO", symbol: "C$", name: "Nicaraguan Córdoba" },
  { code: "NOK", symbol: "kr", name: "Norwegian Krone" },
  { code: "NPR", symbol: "₨", name: "Nepalese Rupee" },
  { code: "NZD", symbol: "NZ$", name: "New Zealand Dollar" },
  { code: "OMR", symbol: "ر.ع.", name: "Omani Rial" },
  { code: "PAB", symbol: "B/.", name: "Panamanian Balboa" },
  { code: "PEN", symbol: "S/", name: "Peruvian Sol" },
  { code: "PGK", symbol: "K", name: "Papua New Guinean Kina" },
  { code: "PHP", symbol: "₱", name: "Philippine Peso" },
  { code: "PKR", symbol: "₨", name: "Pakistani Rupee" },
  { code: "PLN", symbol: "zł", name: "Polish Złoty" },
  { code: "PYG", symbol: "₲", name: "Paraguayan Guaraní" },
  { code: "QAR", symbol: "ر.ق", name: "Qatari Rial" },
  { code: "RON", symbol: "lei", name: "Romanian Leu" },
  { code: "RSD", symbol: "дин.", name: "Serbian Dinar" },
  { code: "RUB", symbol: "₽", name: "Russian Ruble" },
  { code: "SCR", symbol: "SR", name: "Seychellois Rupee" },
  { code: "SDG", symbol: "ج.س.", name: "Sudanese Pound" },
  { code: "SEK", symbol: "kr", name: "Swedish Krona" },
  { code: "SHP", symbol: "£", name: "Saint Helena Pound" },
  { code: "SLL", symbol: "Le", name: "Sierra Leonean Leone" },
  { code: "SOS", symbol: "S", name: "Somali Shilling" },
  { code: "SRD", symbol: "$", name: "Surinamese Dollar" },
  { code: "SSP", symbol: "£", name: "South Sudanese Pound" },
  { code: "STN", symbol: "Db", name: "São Tomé and Príncipe Dobra" },
  { code: "SVC", symbol: "₡", name: "Salvadoran Colón" },
  { code: "SYP", symbol: "£S", name: "Syrian Pound" },
  { code: "SZL", symbol: "E", name: "Swazi Lilangeni" },
  { code: "THB", symbol: "฿", name: "Thai Baht" },
  { code: "TJS", symbol: "ЅМ", name: "Tajikistani Somoni" },
  { code: "TMT", symbol: "m", name: "Turkmenistani Manat" },
  { code: "TND", symbol: "د.ت", name: "Tunisian Dinar" },
  { code: "TOP", symbol: "T$", name: "Tongan Paʻanga" },
  { code: "TRY", symbol: "₺", name: "Turkish Lira" },
  { code: "TTD", symbol: "TT$", name: "Trinidad and Tobago Dollar" },
  { code: "TWD", symbol: "NT$", name: "New Taiwan Dollar" },
  { code: "UAH", symbol: "₴", name: "Ukrainian Hryvnia" },
  { code: "UYU", symbol: "$U", name: "Uruguayan Peso" },
  { code: "UZS", symbol: "лв", name: "Uzbekistani Som" },
  { code: "VES", symbol: "Bs.S", name: "Venezuelan Bolívar Soberano" },
  { code: "VND", symbol: "₫", name: "Vietnamese Đồng" },
  { code: "VUV", symbol: "VT", name: "Vanuatu Vatu" },
  { code: "WST", symbol: "WS$", name: "Samoan Tala" },
  { code: "XCD", symbol: "EC$", name: "East Caribbean Dollar" },
  { code: "XPF", symbol: "₣", name: "CFP Franc" },
  { code: "YER", symbol: "﷼", name: "Yemeni Rial" },
  { code: "ZMW", symbol: "ZK", name: "Zambian Kwacha" },
  { code: "ZWL", symbol: "Z$", name: "Zimbabwean Dollar" },
] as const;

export const sidebarItems: {
  path?: string;
  label: string;
  icon: string;
  isCollapsible?: boolean;
  isBranch?: boolean;
  children?: {
    path: string;
    label: string;
    icon: string;
    permissions: Permission[];
    isBranch?: boolean;
  }[];
  permissions: Permission[];
}[] = [
  {
    path: "/",
    label: "Dashboard",
    icon: "/assets/icons/dashboard.svg",
    permissions: ["admin.dashboardstats"],
  },
  {
    path: "/home",
    label: "Home",
    icon: "/assets/icons/home.svg",
    permissions: ["admin.dashboardstats"],
  },
  {
    path: "/agents-dashboard",
    label: "Home",
    icon: "/assets/icons/home.svg",
    permissions: ["admin.dashboardstats"],
  },
  {
    path: "/company",
    label: "Companies",
    icon: "/assets/icons/companies.svg",
    permissions: ["admin.dashboardstats"],
  },
  {
    path: "/sales",
    label: "Sales and Stock",
    icon: "/assets/icons/sales.svg",
    permissions: ["admin.dashboardstats"],
  },
  {
    path: "/commissions",
    label: "Sales and Commissions",
    icon: "/assets/icons/sales.svg",
    permissions: ["admin.dashboardstats"],
  },
  {
    path: "/produce",
    label: "Produce",
    icon: "/assets/icons/produce.svg",
    permissions: ["admin.dashboardstats"],
  },
  {
    path: "/agents",
    label: "Agents",
    icon: "/assets/icons/agent.svg",
    permissions: ["admin.dashboardstats"],
  },
  {
    path: "/customer",
    label: "Customers",
    icon: "/assets/icons/customer.svg",
    permissions: ["admin.dashboardstats"],
  },
  {
    path: "/business-analytics",
    label: "Business Analytics",
    icon: "/assets/icons/dashboard.svg",
    permissions: ["admin.dashboardstats"],
  },
  {
    label: "Institution",
    icon: "/assets/icons/city.svg",
    permissions: ["admin.dashboardstats"],
    isCollapsible: true,
    children: [
      {
        path: "/country-admin",
        label: "Country Admin",
        icon: "/assets/icons/user-star.svg",
        permissions: ["countryadmin.get"],
      },
      {
        path: "/partners",
        label: "Partners",
        icon: "/assets/icons/user-multiple.svg",
        permissions: ["partners.get"],
      },
      {
        path: "/companies",
        label: "Companies",
        icon: "/assets/icons/city.svg",
        permissions: ["company.get"],
      },
      {
        path: "/superagents",
        label: "Super Agents",
        icon: "/assets/icons/person.svg",
        permissions: ["superagents.get"],
      },
      {
        path: "/sub-agents",
        label: "Sub Agents",
        icon: "/assets/icons/user-square.svg",
        permissions: ["business.get"],
      },
    ],
  },
  {
    label: "Individual",
    icon: "/assets/icons/user-circle.svg",
    permissions: ["admin.dashboardstats"],
    isCollapsible: true,
    children: [
      {
        path: "/digital-entrepreneur",
        label: "Digital Entrepreneur",
        icon: "/assets/icons/user-star.svg",
        permissions: ["digital_entrepreneur.get"],
      },
      {
        path: "/multi-branches",
        label: "Multi-branches",
        icon: "/assets/icons/user-multiple.svg",
        permissions: ["multibranch_business.get"],
      },
      {
        path: "/distributors",
        label: "Distributors",
        icon: "/assets/icons/user-check.svg",
        permissions: ["distributor.get"],
      },
      {
        path: "/business-owners",
        label: "Business Owner",
        icon: "/assets/icons/city.svg",
        permissions: ["business_owners.get"],
        isBranch: true,
      },
    ],
  },
  {
    path: "/videos",
    label: "Videos",
    icon: "/assets/icons/user-check.svg",
    permissions: ["video.get"],
  },
];

export const dummyProducts = [
  {
    agentName: "Sandy Lima",
    image: "/assets/images/prod1.png",
    productName: "Wristwatch",
    amountLeft: "2,500",
    location: "Kiyovu, Kigali, Rwanda",
    category: "Electronics",
    agentDetails: {
      name: "Sandy Lima",
      amountLeft: "2,500",
      location: "Ikotun, Lagos, Nigeria",
      flagUrl: "/assets/icons/nigeria-flag.svg",
      phoneNumber: "+2348012345678",
    },
  },
  {
    agentName: "Kunle Afolayan",
    image: "/assets/images/prod2.png",
    productName: "Stilletos",
    amountLeft: "600",
    location: "Ikotun, Lagos, Nigeria",
    category: "Fashion",
    agentDetails: {
      name: "Kunle Afolayan",
      amountLeft: "300",
      location: "Ikotun, Lagos, Nigeria",
      flagUrl: "/assets/icons/nigeria-flag.svg",
      phoneNumber: "+2348012345679",
    },
  },
  {
    agentName: "Kachiko Adams",
    image: "/assets/images/prod2.png",
    productName: "Shoes",
    amountLeft: "1,500",
    location: "Kiyovu, Kigali, Rwanda",
    category: "Fashion",
    agentDetails: {
      name: "Kachiko Adams",
      amountLeft: "750",
      location: "Kiyovu, Kigali, Rwanda",
      flagUrl: "/assets/icons/nigeria-flag.svg",
      phoneNumber: "+250781234567",
    },
  },
  {
    agentName: "Kunle Afolayan",
    image: "/assets/images/prod1.png",
    productName: "Hand Bags",
    amountLeft: "2,500",
    location: "Ikotun, Lagos, Nigeria",
    category: "Fashion",
    agentDetails: {
      name: "Kunle Afolayan",
      amountLeft: "1250",
      location: "Ikotun, Lagos, Nigeria",
      flagUrl: "/assets/icons/nigeria-flag.svg",
      phoneNumber: "+2348012345679",
    },
  },
  {
    agentName: "Isreal Someone",
    image: "/assets/images/prod2.png",
    productName: "Ropes",
    amountLeft: "5,000",
    location: "Kiyovu, Kigali, Rwanda",
    category: "Home & Garden",
    agentDetails: {
      name: "Isreal Someone",
      amountLeft: "2500",
      location: "Kiyovu, Kigali, Rwanda",
      flagUrl: "/assets/icons/nigeria-flag.svg",
      phoneNumber: "+250781234568",
    },
  },
];

export const productCardColors = [
  "#E8EDEA",
  "#E6F2FF",
  "#FFF4E6",
  "#FDE9E8",
  "#E6F2F2",
];

export const permissionRouteMap: Record<string, string[]> = {
  "admin.dashboardstats": ["/business-analytics", "/products"],
  "admin.getCurrent": ["/", "/settings"],
  "partners.get": ["/partners", "/partners/:id"],
  "partners.getSingle": ["/partners/:id"],
  "superagents.get": ["/superagents"],
  "superagents.getSingle": ["/superagents/:id"],
  "business.get": ["/sub-agents"],
  "business.getSingle": ["/sub-agents/:id"],
  "video.get": ["/videos", "/videos/:id"],
  "countryadmin.get": ["/country-admin"],
  "countryadmin.getSingle": ["/country-admin/:id"],
  "company.get": ["/companies"],
  "company.getSingle": ["/companies/:id"],
  "multibranch_business.getSingle": ["/multi-branches/:id"],
  "multibranch_business.get": ["/multi-branches"],
  "distributor.create": ["/distributors/create"],
  "distributor.getSingle": ["/distributors/:id"],
  "distributor.get": ["/distributors"],
  "digital_entrepreneur.getSingle": ["/digital-entrepreneur/:id"],
  "digital_entrepreneur.get": ["/digital-entrepreneur"],
  "business_owners.getSingle": ["/business-owners/:id", "/branches/:id"],
  "business_owners.get": ["/business-owners", "/branches"],
};
